
# list of datasets that can be used as reference files, available on current machine
reference_files:

    # test reference with chr22 only
    test_chr22:
        genome: /smbshare/references/test_chr22/chr22_with_ERCC92.fa
        annotation: /smbshare/references/test_chr22/chr22_with_ERCC92.gtf
        starpath: /smbshare/references/test_chr22/star/
        snpdatabase: /smbshare/references/test_chr22/chr22_variants.vcf
        mkrefpath: /smbshare/references/test_chr22/mkref/
        vdjrefpath: None

    # cellranger reference human GRCh38-2020-A dataset
    cellranger_human_GRCh38-2020-A:
        genome: /smbshare/references/cellranger/gex-GRCh38-2020-A/mkref/fasta/genome.fa
        annotation: /smbshare/references/cellranger/gex-GRCh38-2020-A/mkref/genes/genes.gtf
        starpath: /smbshare/references/cellranger/gex-GRCh38-2020-A/star
        snpdatabase: /smbshare/references/snp_database/00-All.EnsemblSorted.Sort.vcf
        mkrefpath: /smbshare/references/cellranger/gex-GRCh38-2020-A/mkref
        vdjrefpath: /smbshare/references/cellranger/vdj-GRCh38-alts-ensembl-4.0.0/

# userid map is a dictionary to map the username to a uniform, concise user id
userid_map:
    matteo.bonfanti: "matteo"

# standard storage directory where the processing data are written
datapath: "/smbshare/"
# long-term storage unit, with safe storage and backup strategy
ltstoragepath: "/smbshare/"
# path where scratch data can be written
scratchpath: "/home/scratch/"
# path where singularity images will be stored
singularitypath: "/home/scratch/"

# directories to mount with singularity
singularitymount:
- "/smbshare/"
- "/home/scratch/"

# variable to define whether a scheduler is available in this platform, either None or the name of a
# config file that should be available in the config dir, e.g. "pbs.yaml"
scheduler: null
